pipeline {
    agent any

    environment {
        AWS_REGION = "ap-south-1"   // your region
        S3_BUCKET = "react-bucket-aws-ga"   // your S3 bucket name
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo "Checking out code..."
                git branch: 'main', url: 'https://github.com/vasu-004/react-app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                echo "Installing dependencies..."
                sh 'npm install'
            }
        }

        stage('Build React App') {
            steps {
                echo "Building React App..."
                sh 'npm run build'
            }
        }

        stage('Deploy to S3') {
            steps {
                withAWS(credentials: 'aws-creds', region: "${AWS_REGION}") {
                    echo "Uploading files to S3..."
                    sh """
                        aws s3 sync build/ s3://${S3_BUCKET}/ \
                        --delete \
                        --cache-control "max-age=86400"
                    """
                }
            }
        }
    }

    post {
        success {
            echo "✅ Frontend successfully deployed to S3!"
        }
        failure {
            echo "❌ Deployment failed!"
        }
    }
}
